#define FLOAT_T float

/**** Prototypes of functions automatically generated by scikinC ****/
// Resolution steps
FLOAT_T* resolution_tX         (FLOAT_T*, const FLOAT_T*);
FLOAT_T* resolution_tY_inverse (FLOAT_T*, const FLOAT_T*);
FLOAT_T* resolution_dnn        (FLOAT_T*, const FLOAT_T*);

// Covariance steps
FLOAT_T* covariance_tX         (FLOAT_T*, const FLOAT_T*);
FLOAT_T* covariance_tY_inverse (FLOAT_T*, const FLOAT_T*);
FLOAT_T* covariance_dnn        (FLOAT_T*, const FLOAT_T*);


/**** Additional functions wrapping generated functions together ****/

// Resolution entry point
FLOAT_T* resolution (FLOAT_T* output, const FLOAT_T* input, const FLOAT_T* random)
{
    // Rename constants defined at compile time 
    const int nInputs = RESOLUTION_NUM_FEATURES;
    const int nOutputs = RESOLUTION_NUM_OUTPUTS;
    const int nRandom = COVARIANCE_NUM_RANDOM;

    // Instanciate variables in the stack.
    FLOAT_T buf[nInputs + nOutputs + nRandom];
    int i;
    
    // Preprocessing
    resolution_tX(buf, input);
    
    // Concatenate preprocessed features and random noise
    for (i = 0; i < nRandom; ++i)
        buf[i + nInputs] = random[i];
    
    // Execute the generator
    resolution_dnn(buf, buf);
    
    // Apply the inverse postprocessing transformation
    resolution_tY_inverse(output, buf);
    
    return output;
}

// Covariance entry point
FLOAT_T* covariance (FLOAT_T* output, const FLOAT_T* input, const FLOAT_T* random)
{
    // Rename constants defined at compile time 
    const int nInputs = COVARIANCE_NUM_FEATURES;
    const int nOutputs = COVARIANCE_NUM_OUTPUTS;
    const int nRandom = COVARIANCE_NUM_RANDOM;
    
    // Instanciate variables in the stack.
    FLOAT_T buf[nInputs + nOutputs + nRandom];
    int i;
    
    // Preprocessing
    covariance_tX(buf, input);
    
    // Concatenate preprcessed features and random noise
    for (i = 0; i < nRandom; ++i)
        buf[i + nInputs] = random[i];
    
    // Execute the DNN
    covariance_dnn(buf, buf);
    
    // Apply the inverse postprocessing transformation
    covariance_tY_inverse(output, buf);
    
    return output;
}