# .github/workflows/shared.yml
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore file timestamps
        run: |
            git log -1 --format="%at" -- notebooks/workflow/envs/lhcb.def

      - name: Retrieve secrets
        run: |
            mkdir -p /tmp/artifacts
            cat <<EOF > /tmp/artifacts/secrets.yaml
            ${{ secrets.SECRETS_YAML }}
            EOF

      - name: Snakemake workflow
        uses: landerlini/apptainer-gha-runner/workflow@main
        with:
            workdir: notebooks
            target: ${{ inputs.target }}
            report: report-${{ inputs.name }}
            snakefile: workflow/Snakefile
            config: |
                secrets_file: /tmp/artifacts/secrets.yaml
            profile: |
                rerun-incomplete: True
                keep-going: True

                software-deployment-method: apptainer
                local-storage-prefix: /tmp
                apptainer-args: -B /home -B /cvmfs -B /tmp --nv --writable-tmpfs --no-mount /usr
                keep-storage-local-copies: true

                jobs: 1
                cores: 8

                default-resources:
                  mem_mb: 2000
                  millicpu: 1000

                resources:
                  mem_mb: 64000
                  millicpu: 32000
                  gpu: 1

        

