name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
    #run-workflow:
    #    uses: ./.github/workflows/shared.yaml
    #    with:
    #        name: deploy
    #        target: deploy
    #        additional_profile: |
    #            rerun-triggers: mtime
    #    secrets:
    #        SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

    upload_dot_c:
      runs-on: ubuntu-latest
      container: harbor.cloud.infn.it/unpacked/aiinfn-gha-runner:latest
    #  needs: run-workflow
      steps:
        - name: Install missing libraries
          run: |
            sudo apt-get update 
            sudo apt-get install -y xz-utils
 
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Retrieve secrets
          run: |
              mkdir -p /tmp/artifacts
              cat <<EOF > /tmp/artifacts/secrets.yaml
              ${{ secrets.STORAGE_SECRETS }}
              EOF

        - name: compress_file
          run: |
              cd notebooks
              export SNAKEMAKE_PROFILE=$PWD//workflow/profile/
              snakemake compress_dotC \
                --allowed-rules compress_dotC \
                --jobs 1 \
                --config secrets_file=/tmp/artifacts/secrets.yaml \
                --rerun-incomplete \
                --local-storage-prefix /tmp 
                
        - name: Upload compressed model
          uses: actions/upload-artifact@v4
          with:
            name: compiled_model.C.xz
            path: /tmp/compiled_model.C.xz

    compile:
      needs: upload_dot_c
      strategy:
        matrix:
          runner: [ubuntu-latest, ubuntu-24.04-arm]
          container: ["centos:7", "almalinux:9"]
          optimization: [-O0, -O2]

      runs-on: ${{ matrix.runner }}
      container: ${{ matrix.container }}
      
      steps:
        - name: Install missing libraries
          run: |
            apt-get update 
            apt-get install -y xz gcc
 
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: compiled_model.C.xz
            path: ./compiled_model.C.xz
    
        - name: Compile with GCC
          run: |
            xz -f compiled_model.C.xz
            mkdir -p build
            gcc compiled_model.C \
                ${{ matrix.optimization }} \
                -D RESOLUTION_NUM_FEATURES=12  \
                -D RESOLUTION_NUM_OUTPUTS=9  \
                -D RESOLUTION_NUM_RANDOM=128  \
                -D COVARIANCE_NUM_FEATURES=15  \
                -D COVARIANCE_NUM_OUTPUTS=15  \
                -D COVARIANCE_NUM_RANDOM=128  \
                -o /tmp/compiled_model.so  \
                -lm  \
                --shared  \
                -fPIC \
                -o build/compiled_model.so  

        - name: Upload compiled shared object
          uses: actions/upload-artifact@v4
          with:
            path: build/compiled_model.so
            name: trk-${{ matrix.runner }}-${{ matrix.container }}${{ matrix.optimization }}.so

