name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup singularity
        run: |
            echo "Setting up singularity"
            cat <<EOF > /tmp/singularity_exec
            #!/bin/bash   
            TMPFILE=/tmp/$RANDOM.sh
            cd /tmp
            cat > \$TMPFILE
            echo \$TMPFILE
            apptainer -d exec \\
                -w /tmp \\
                --no-home \\
                --no-mount /dev \\
                --writable-tmpfs \\
                /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/ \\
                $@ /bin/bash \$TMPFILE
            rm \$TMPFILE
            EOF
            cat /tmp/singularity_exec

            chmod +x /tmp/singularity_exec 
            /tmp/singularity_exec <<EOF
                echo "Singularity ok"
            EOF

      - name: Run Snakemake
        run: |
          /tmp/singularity_exec <<EOF
              snakemake reports/preprocessing.html
          EOF
        

