name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - uses: actions/checkout@v4
      
                # /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/ 
      - name: Setup singularity
        run: |
            echo "Setting up singularity"
            mkdir -p /tmp/apptainer_tmp
            mkdir -p /tmp/apptainer_cache

            cat <<EOF > /tmp/myrunner
            #!/bin/bash   
            TMPFILE=/tmp/runner-cmd/$RANDOM.sh
            mkdir -p \$(dirname \$TMPFILE)
            echo "cd /repo" > \$TMPFILE
            cat >> \$TMPFILE
            echo \$TMPFILE

            cd /tmp
            APPTAINER_CACHEDIR=/tmp/apptainer_cache \\
            APPTAINER_TMPDIR=/tmp/apptainer_tmp \\
            apptainer exec \\
                -B /cvmfs:/cvmfs:ro \\
                -B \$TMPFILE:/mycommand.sh:ro \\
                -B $PWD:/repo \\
                --scratch /workarea \\
                /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/lb-trksim-train-singularity:v0p9b \\
                /bin/bash /mycommand.sh \\
            rm \$TMPFILE
            EOF
            cat /tmp/myrunner

            chmod +x /tmp/myrunner 
            /tmp/myrunner <<EOF
                echo "Singularity ok"
            EOF

      - name: Run Snakemake
        run: |
          /tmp/myrunner <<EOF
              ls
              cd notebooks
              
              snakemake reports/preprocessing.html
          EOF
        

