name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snakemake
        run: |
          cd notebooks
          singularity run /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/ \
              snakemake reports/preprocessing.html
        

