name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
    release-cycle:
        uses: ./.github/workflows/shared.yaml
        with:
            name: ${{ github.head_ref }}
            target: deploy
            additional_profile: |
                rerun-triggers: mtime
        secrets:
            SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

