name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
#      - name: Run preprocessing
#        uses: landerlini/apptainer-gha-runner/container@main
#        with:
#            image: "/cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/"
#            run: |
#                cd notebooks 
#                export SNAKEMAKE_PROFILE=workflow/profile
#                snakemake preprocessing
#                snakemake preprocessing --report

      - name: Run preprocessing
        uses: landerlini/apptainer-gha-runner/workflow@main
        with:
            workdir: notebooks
            target: preprocessing
            report: report
            snakefile: workflow/Snakefile
            profile: |
                rerun-incomplete: True
                keep-going: True


                software-deployment-method: apptainer
                local-storage-prefix: /tmp
                apptainer-args: -B /home -B /cvmfs -B /tmp --nv --writable-tmpfs --no-mount /usr
                keep-storage-local-copies: true

                jobs: 1
                cores: 8

                default-resources:
                  mem_mb: 2000
                  millicpu: 1000

                resources:
                  mem_mb: 64000
                  millicpu: 32000
                  gpu: 1


      - name: Create report
        uses: landerlini/apptainer-gha-runner/container@main
        with:
            image: "/cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/"
            run: |
                cd notebooks 
                export SNAKEMAKE_PROFILE=workflow/profile
                snakemake --report /tmp/artifacts/report.html \
                    preprocessing 


    #  - name: Run test workflow
    #    uses: landerlini/apptainer-gha-runner/workflow@main
    #    with:
    #        workdir: notebooks
    #        target: example.md
    #        report: report
    #        profile: |
    #            cores: 1
    #            forceall: true
    #
                

        

