name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup singularity
        run: |
            echo "Setting up singularity"
            cat <<EOF > exec
            \#!/bin/bash   
            TMPFILE=/tmp/$RANDOM.sh
            cat > $TMPFILE
            echo $TMPFILE
            singularity run \\
                --compat \\
                -B /cvmfs \\
                -B $PWD:/repo \\
                /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/ \\
                "$@" /bin/bash $TMPFILE
            rm $TMPFILE
            EOF

            chmod +x exec 
            exec <<EOF
                echo "Singularity ok"
            EOF

      - name: Run Snakemake
        run: |
          exec <<EOF
              singularity run 
                  snakemake reports/preprocessing.html
          EOF
        

