name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - uses: actions/checkout@v4
      
                # /cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/ 
      - name: Setup singularity
        run: |
            echo "Setting up singularity"
            apptainer build --sandbox /tmp/image docker://harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3 
            mkdir /tmp/image/dev
            cat <<EOF > /tmp/myrunner
            #!/bin/bash   
            TMPFILE=/tmp/$RANDOM.sh
            cd /tmp
            cat > \$TMPFILE
            echo \$TMPFILE
            mkdir /dev
            apptainer -d exec \\
                -w /tmp \\
                --no-home \\
                --no-mount dev,/dev \\
                $@ \\
                /tmp/image \\
                /bin/bash \$TMPFILE
            rm \$TMPFILE
            EOF
            cat /tmp/myrunner

            chmod +x /tmp/myrunner 
            /tmp/myrunner <<EOF
                echo "Singularity ok"
            EOF

      - name: Run Snakemake
        run: |
          /tmp/myrunner <<EOF
              snakemake reports/preprocessing.html
          EOF
        

