name: Train models

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pull_request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    trk-2016MagUp-Sim10b:
        uses: LamarrSim/release-models/.github/workflows/release.yaml@main
        permissions:
          contents: write
          pull-requests: write
        with:
            name: pp-2016-MU-Sim10b-${{ github.head_ref }}
            snakemake_dir: notebooks
            target: deploy validate_acceptance validate_efficiency validate_resolution validate_covariance
            additional_config: |
                training_data:
                    - training-data/2016MU-sim10b/LamarrTraining.root
            additional_profile: |
                rerun-triggers: mtime
            generated_model_path: /tmp/s3models/lamarr-train/models/compiled_model.c
        secrets:
            SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

