name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
    release-cycle:
        uses: ./.github/workflows/shared.yaml
        permissions:
          contents: write
        with:
            name: ${{ github.head_ref }}
            target: deploy validate_acceptance validate_efficiency validate_resolution validate_covariance
            additional_profile: |
                rerun-triggers: mtime
            generated_model_path: /tmp/s3models/lamarr-train/models/compiled_model.c
        secrets:
            SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

