name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: aiinfn-lamarrsim-gpu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run test action
        uses: landerlini/apptainer-gha-runner@main
        with:
            image: "/cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/"
            run: |
                cd notebooks 
                snakemake example.md 

      - name: Create report
        uses: landerlini/apptainer-gha-runner@main
        with:
            image: "/cvmfs/unpacked.infn.it/harbor.cloud.infn.it/unpacked/jlab-ai-infn:2.0.0-ai1.3/"
            run: |
                cd notebooks 
                snakemake --report example.md 
        

