name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
    #run-workflow:
    #    uses: ./.github/workflows/shared.yaml
    #    with:
    #        name: deploy
    #        target: deploy
    #        additional_profile: |
    #            rerun-triggers: mtime
    #    secrets:
    #        SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

    upload_dot_c:
      runs-on: aiinfn-lamarrsim-gpu
    #  needs: run-workflow
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Retrieve secrets
          run: |
              mkdir -p /tmp/artifacts
              cat <<EOF > /tmp/artifacts/secrets.yaml
              ${{ secrets.SECRETS_YAML }}
              EOF

        - name: compress_file
          run: |
              export SNAKEMAKE_PROFILE=$PWD/notebooks/workflow/profile/
              snakemake compress_dotC \
                --allowed-rules compress_dotC \
                --jobs 1 \
                --rerun-incomplete \
                --local-storage-prefix /tmp 
                
        - name: Upload compressed model
          uses: actions/upload-artifact@v4
          with:
            name: compiled_model.C.xz
            path: /tmp/compiled_model.C.xz

