name: Train models

on:
  pull_request:
    branches:
      - main

jobs:
  run-snakemake:
    environment: full-train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snakemake
        run: |
          cd notebooks
          snakemake reports/preprocessing.html
        

